import React from 'react';
import './Disclaimer.css';

export default function Disclaimer() {
  return (
    <div className="policy-container">
      <h1>Disclaimer</h1>
      <p className="last-updated">Last Updated: March 27, 2026</p>

      <section>
        <h2>Medical & Insurance Disclaimer</h2>
        <p>
          <strong>IMPORTANT:</strong> Lower My Medical Bills provides automated analysis tools for educational purposes only. 
          We are not insurance brokers, healthcare providers, legal counsel, or medical professionals.
        </p>
      </section>

      <section>
        <h2>No Professional Advice</h2>
        <p>
          The analysis, findings, confidence scores, and recommendations provided by our Services are not:
        </p>
        <ul>
          <li>Professional medical or healthcare advice.</li>
          <li>Legal advice or opinion from a licensed attorney.</li>
          <li>Insurance guidance from a licensed insurance broker or agent.</li>
          <li>A substitute for consulting with qualified professionals (doctors, lawyers, or insurance agents).</li>
        </ul>
        <p>
          Reliance on our Services is at your sole discretion and risk. You should always consult with appropriate licensed 
          professionals before making healthcare, legal, or insurance decisions.
        </p>
      </section>

      <section>
        <h2>Algorithm Limitations</h2>
        <p>
          Our pattern-matching algorithm analyzes EOB documents to identify potential issues but operates with inherent limitations:
        </p>
        <ul>
          <li><strong>Incomplete Data:</strong> Your EOB may not contain all fields (e.g., deductible accumulator, remaining OOP). 
              Confidence scores reflect these data gaps.</li>
          <li><strong>Plan Complexity:</strong> Health insurance plans vary widely. Our algorithm may not fully capture plan-specific rules, 
              exclusions, or bundling.</li>
          <li><strong>False Positives:</strong> We may flag charges as problematic when they are actually correct under your specific plan. 
              Always verify before acting.</li>
          <li><strong>False Negatives:</strong> We may miss genuine errors. Your independent review is essential.</li>
          <li><strong>No Real-Time Updates:</strong> Our analysis reflects information available on your uploaded EOB. Plan changes, 
              retroactive adjustments, or processing delays are not captured.</li>
        </ul>
      </section>

      <section>
        <h2>Appeal Outcomes Are Not Guaranteed</h2>
        <p>
          An appeal having merit under our analysis does NOT guarantee successful resolution. Success depends on:
        </p>
        <ul>
          <li>Provider responsiveness and willingness to review.</li>
          <li>Insurance carrier policies and appeal procedures.</li>
          <li>Quality and completeness of supporting documentation.</li>
          <li>Regulatory and state-specific rules.</li>
          <li>Timing and procedural deadlines.</li>
        </ul>
        <p>
          <strong>Lower My Medical Bills assumes no responsibility for appeal outcomes, whether positive or negative.</strong>
        </p>
      </section>

      <section>
        <h2>No Guarantee of Accuracy</h2>
        <p>
          While we strive for accuracy, our findings are generated by automated logic and should not be considered authoritative. 
          We make no warranty that our analysis is:
        </p>
        <ul>
          <li>100% accurate or error-free.</li>
          <li>Complete or comprehensive.</li>
          <li>Applicable to your specific plan or situation.</li>
          <li>Up-to-date with current insurance regulations or plan changes.</li>
        </ul>
      </section>

      <section>
        <h2>User Responsibility</h2>
        <p>
          You are solely responsible for:
        </p>
        <ul>
          <li>Verifying all findings and recommendations independently.</li>
          <li>Checking your plan documents to confirm coverage rules and limits.</li>
          <li>Consulting with your insurance provider or benefits administrator before disputing charges.</li>
          <li>Meeting appeal deadlines and procedural requirements.</li>
          <li>Making final decisions about whether to pursue appeals.</li>
          <li>Reviewing all correspondence from providers and insurers carefully.</li>
        </ul>
      </section>

      <section>
        <h2>No Warranty of Uptime or Security</h2>
        <p>
          We do not warrant that:
        </p>
        <ul>
          <li>The Services will be available at all times without interruption.</li>
          <li>The Services will be free from errors, bugs, or malfunction.</li>
          <li>Your EOB data will be protected from unauthorized access or breaches (though we use industry-standard security).</li>
          <li>The platform will remain compatible with all browsers or devices.</li>
        </ul>
      </section>

      <section>
        <h2>Changes & Updates</h2>
        <p>
          We may modify, suspend, or discontinue any aspect of the Services at any time without liability. The rules, 
          thresholds, and confidence calculations used in our algorithm may change as we improve our product.
        </p>
      </section>

      <section>
        <h2>Regulatory Disclaimer</h2>
        <p>
          Lower My Medical Bills is not:
        </p>
        <ul>
          <li>A licensed insurance agency.</li>
          <li>A law firm or practice of law.</li>
          <li>A healthcare provider.</li>
          <li>A fiduciary or agent for any user.</li>
          <li>Regulated by the SEC, FINRA, or insurance regulators (unless required by applicable law).</li>
        </ul>
      </section>

      <section>
        <h2>Acknowledgment</h2>
        <p>
          <strong>By using the Services, you acknowledge that you have read this Disclaimer, understand its contents, 
          and accept the risks inherent in using automated analysis tools for healthcare decision-making.</strong>
        </p>
      </section>

      <section>
        <h2>Contact Us</h2>
        <p>
          If you have questions or concerns about our Disclaimer or Services, please contact us:
        </p>
        <p>
          <strong>Lower My Medical Bills</strong><br />
          Email: <strong>support@lowermymedicalbills.com</strong><br />
          Website: <strong>www.lowermymedicalbills.com</strong>
        </p>
      </section>
    </div>
  );
}
